import Authprovider from './component/Authprovider/Authprovider'
import { Josefin_Slab } from "next/font/google";
import "./globals.css";

const josefin_slab = Josefin_Slab({
  subsets: ["latin"],
  variable: "--font-josefin-slab",
  weight: '600',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${josefin_slab.variable}`}>
        <Authprovider>
        {children}
        </Authprovider></body>
    </html>
  );
}
